/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesAiAgentsRouteImport } from './routes/courses.ai-agents'
import { Route as CoursesAzureCloudRouteImport } from './routes/courses.azure-cloud'
import { Route as CoursesCyberSecurityRouteImport } from './routes/courses.cyber-security'
import { Route as CoursesGenerativeAiRouteImport } from './routes/courses.generative-ai'
import { Route as CoursesNetworkingCcnaRouteImport } from './routes/courses.networking-ccna'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesAiAgentsRoute = CoursesAiAgentsRouteImport.update({
  id: '/courses/ai-agents',
  path: '/courses/ai-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesAzureCloudRoute = CoursesAzureCloudRouteImport.update({
  id: '/courses/azure-cloud',
  path: '/courses/azure-cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCyberSecurityRoute = CoursesCyberSecurityRouteImport.update({
  id: '/courses/cyber-security',
  path: '/courses/cyber-security',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesGenerativeAiRoute = CoursesGenerativeAiRouteImport.update({
  id: '/courses/generative-ai',
  path: '/courses/generative-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesNetworkingCcnaRoute = CoursesNetworkingCcnaRouteImport.update({
  id: '/courses/networking-ccna',
  path: '/courses/networking-ccna',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses/ai-agents': typeof CoursesAiAgentsRoute
  '/courses/azure-cloud': typeof CoursesAzureCloudRoute
  '/courses/cyber-security': typeof CoursesCyberSecurityRoute
  '/courses/generative-ai': typeof CoursesGenerativeAiRoute
  '/courses/networking-ccna': typeof CoursesNetworkingCcnaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses/ai-agents': typeof CoursesAiAgentsRoute
  '/courses/azure-cloud': typeof CoursesAzureCloudRoute
  '/courses/cyber-security': typeof CoursesCyberSecurityRoute
  '/courses/generative-ai': typeof CoursesGenerativeAiRoute
  '/courses/networking-ccna': typeof CoursesNetworkingCcnaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses/ai-agents': typeof CoursesAiAgentsRoute
  '/courses/azure-cloud': typeof CoursesAzureCloudRoute
  '/courses/cyber-security': typeof CoursesCyberSecurityRoute
  '/courses/generative-ai': typeof CoursesGenerativeAiRoute
  '/courses/networking-ccna': typeof CoursesNetworkingCcnaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses/ai-agents'
    | '/courses/azure-cloud'
    | '/courses/cyber-security'
    | '/courses/generative-ai'
    | '/courses/networking-ccna'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses/ai-agents'
    | '/courses/azure-cloud'
    | '/courses/cyber-security'
    | '/courses/generative-ai'
    | '/courses/networking-ccna'
  id:
    | '__root__'
    | '/'
    | '/courses/ai-agents'
    | '/courses/azure-cloud'
    | '/courses/cyber-security'
    | '/courses/generative-ai'
    | '/courses/networking-ccna'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesAiAgentsRoute: typeof CoursesAiAgentsRoute
  CoursesAzureCloudRoute: typeof CoursesAzureCloudRoute
  CoursesCyberSecurityRoute: typeof CoursesCyberSecurityRoute
  CoursesGenerativeAiRoute: typeof CoursesGenerativeAiRoute
  CoursesNetworkingCcnaRoute: typeof CoursesNetworkingCcnaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/ai-agents': {
      id: '/courses/ai-agents'
      path: '/courses/ai-agents'
      fullPath: '/courses/ai-agents'
      preLoaderRoute: typeof CoursesAiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/azure-cloud': {
      id: '/courses/azure-cloud'
      path: '/courses/azure-cloud'
      fullPath: '/courses/azure-cloud'
      preLoaderRoute: typeof CoursesAzureCloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/cyber-security': {
      id: '/courses/cyber-security'
      path: '/courses/cyber-security'
      fullPath: '/courses/cyber-security'
      preLoaderRoute: typeof CoursesCyberSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/generative-ai': {
      id: '/courses/generative-ai'
      path: '/courses/generative-ai'
      fullPath: '/courses/generative-ai'
      preLoaderRoute: typeof CoursesGenerativeAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/networking-ccna': {
      id: '/courses/networking-ccna'
      path: '/courses/networking-ccna'
      fullPath: '/courses/networking-ccna'
      preLoaderRoute: typeof CoursesNetworkingCcnaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesAiAgentsRoute: CoursesAiAgentsRoute,
  CoursesAzureCloudRoute: CoursesAzureCloudRoute,
  CoursesCyberSecurityRoute: CoursesCyberSecurityRoute,
  CoursesGenerativeAiRoute: CoursesGenerativeAiRoute,
  CoursesNetworkingCcnaRoute: CoursesNetworkingCcnaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
